#服务器相关配置
service:
  port: 80
  name: "server"

#mysql数据库
mysql:
  username: "root"
  password: "admin123"
  database: "server"
  url: "127.0.0.1"

#redis数据库
redis:
  addr: "xlei.love:6379"
  db: 0
  password: "admin123"
  poolsize: 1000
  maxidleconns: 1000
  minidleconns: 10
  connMaxIdleTime: 10

#Jwt
jwt:
  time: 12
  key: "welcome to use Tally by M"

#日志相关配置
Logs:
  leave: "info"
  prefix: "server"
  path: "./log/"
  maxsize: 100

