#服务器相关配置
service:
  port: 80
  name: "server"
  readTime: 10
  writeTime: 10
  maxHeaderBytes: 1

#mysql数据库
mysql:
  username: "root"
  password: "admin123"
  database: "server"
  url: "127.0.0.1"

#redis数据库
redis:
  addr: "127.0.0.1:6379"
  db: 0
  password: "admin123"
  poolsize: 1000
  maxidleconns: 1000
  minidleconns: 10
  connMaxIdleTime: 10
  Times: 5

#Jwt
jwt:
  time: 24
  key: "ha ha ha xiao xue sheng"

#日志相关配置
Logs:
  leave: "info"
  prefix: "server"
  path: "./log/"
  maxsize: 100

#cos
tencentCos:
  url: "https://tally-1308109276.cos.ap-nanjing.myqcloud.com/"
  secretId: "AKIDfBRQAdpkPnukJceOr52JK4XjeIgmb9RS"
  secretKey: "lFRTFkzziAMIyNULvEG0VkofGahZBWaN"

#  协程池
Pool:
  size: 10
  num: 10
